# Generated by Django 4.2.22 on 2025-06-17 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('animal_type', models.CharField(choices=[('chat', 'Chat'), ('chien', 'Chien'), ('lapin', 'Lapin')], max_length=20)),
                ('breed', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('weight', models.FloatField()),
                ('sex', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle')], max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='owners.owner')),
            ],
        ),
    ]
