# Generated by Django 5.2.1 on 2025-05-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('animal_type', models.CharField(choices=[('cat', 'Chat'), ('dog', 'Chien'), ('rabbit', 'Lapin')], max_length=50)),
                ('owner', models.CharField(max_length=100)),
            ],
        ),
    ]
